### PR TITLE
Refactor, pt2

### PR DESCRIPTION
**Pull request by bodrovis**
* Adds https://github.com/nathanvda/cocoon gem to simplify building nested fields
* Adds `internal_name` for stalls. This is just for the owner's convenience. For example, rooms in a hotel have numbers: 101, 405 etc. Here, we have internal names
* Fixes some issues with the booking
* Implements form_with - that's a new method to build forms. Just wanted to show it
* Adds seeds data. Run `rails db:seed` to populate demo users

Some thoughts:

* Users should not be able to select anyone as an owner or a booker. They should be able to make booking only for themselves. Same applies to creating stables. But for that we'll need some authentication, so let's put it aside for now
* Stall should not have many users directly. It already has many users via the booking.
* Booking dates should be added
* Some tests should be written, I'd leave it for you as a "homework"

Please let me know what you think @Femchengdu :)

### CODE REVIEW

**Comment by Femchengdu** [comment]
Great ideas so far, to be honest I don't know what to write test for at this point. Do I write tests for the code that has already been written or focus on testing code that I am yet to write?

**Comment by bodrovis** [comment]
@Femchengdu It depends. Extreme programming approach means "write tests then write code". But well, I don't think we need to use such approach now. Let's at least test some models for now, maybe integration tests with Capybara for a handful of scenarios: creation of something, editing etc.

**Comment by bodrovis** [comment]
I mean, try to write something. Then we'll see and I'll help if needed.

**Comment by Femchengdu** [comment]
Okay.

**Pull request merged**
